### ISSUE TITLE
 Linter ignores .chtexrc file on Windows

### ISSUE THREAD

**Issue by armnrd** [SublimeLinter/SublimeLinter-chktex#15]
What is the proper way to pass settings to chktex through SublimeLinter settings? I want chktex to read the .chktexrc in my home folder, but changing the settings doesn't seem to do anything.

My SublimeLinter.sublime-settings:
```
// SublimeLinter Settings - User
{
    "user": {
     "linters": {
        // The name of the linter you installed
        "chktex": {
                // Disables the linter. The default here is 'not set'
                "disable": false,

                // Additional arguments for the command line. Either a string
                // or an array. If set to a string, we 'shlex.split' it*.
                // E.g. '--ignore D112' or ['--config', './.config/foo.ini']
                //
                // * Note: Use proper quoting around paths esp. on Windows!
                "args": ["-l C:\\Usesrs\\Arindam\\.chktexrc"],

                // Path to the executable to be used. Either a string or an
                // array. E.g. ['nvm', 'exec', '8.6', 'eslint']
                //"executable": "<automatically set>",

                // A modified runtime environment for the lint job. Settings here
                // override the default, inherited ENV.
                "env": {},

                // Exclude files that match the given pattern(s).
                "excludes": [],

                // Suppress errors that match the the given pattern(s).
                // Either a 'string' or an 'array'. Each input string is handled as
                // a case-insensitive regex pattern and matched against the
                // error_type, code, and message. If it matches, the error will be
                // thrown away.
                // E.g. ["warning: ", "W3\d\d: ", "missing <!DOCTYPE> declaration"]
                "filter_errors": [],

                // Lint mode determines when the linter is run. The linter setting
                // will take precedence over the global setting.
                //"lint_mode": "manual",

                // Determines for which views this linter will run.
                "selector": "",

                // A list of additional style definition blocks.
                "styles": [
                    {
                        // Instead of 'types' you can specify error 'codes' for
                        // a style definition block
                        "codes": [""]
                    }
                ],

                // The current working dir the lint job will run in.
                "working_dir": "",

                // **Only valid for PythonLinter**
                // Specify which python to use. Either a number or full path
                // to a python binary. SL will then basically use 'python -m'
                // to run the linter.
                //"python": 3,

                // **Only valid for NodeLinter**
                // If true, will *not* use a globally installed binary
                "disable_if_not_dependency": false
            }
        }
    }
}```

**Comment by kaste** [comment]
Hi @armnrd! You're wrapping everything under a "user" key, but there is no such thing.

**Comment by armnrd** [comment]
Hi @kaste, I took everything outside the key, but SublimeLinter still behaves the same way. Could you get it to work as you want on Windows? If you did, could you share your config?

**Comment by kaste** [comment]
Gnerally you should enable debug mode in the settings. From looking at "args", "-l foo" is not one argument, but when providing this as an array you must provide each argument separately.

**Comment by armnrd** [comment]
Separating the argument out did the trick! Thanks. Here's what my config looks like now:

// SublimeLinter Settings - User
{
    "linters": {
    // The name of the linter you installed
        "chktex": {
            // Disables the linter. The default here is 'not set'
            "disable": false,

            // Additional arguments for the command line. Either a string
            // or an array. If set to a string, we 'shlex.split' it*.
            // E.g. '--ignore D112' or ['--config', './.config/foo.ini']
            //
            // * Note: Use proper quoting around paths esp. on Windows!
            "args": ["-l", "C:\\Users\\Arindam\\.chktexrc"],

            // Path to the executable to be used. Either a string or an
            // array. E.g. ['nvm', 'exec', '8.6', 'eslint']
            //"executable": "<automatically set>",

            // A modified runtime environment for the lint job. Settings here
            // override the default, inherited ENV.
            "env": {},

            // Exclude files that match the given pattern(s).
            "excludes": [],

            // Suppress errors that match the the given pattern(s).
            // Either a 'string' or an 'array'. Each input string is handled as
            // a case-insensitive regex pattern and matched against the
            // error_type, code, and message. If it matches, the error will be
            // thrown away.
            // E.g. ["warning: ", "W3\d\d: ", "missing <!DOCTYPE> declaration"]
            "filter_errors": [],

            // Lint mode determines when the linter is run. The linter setting
            // will take precedence over the global setting.
            //"lint_mode": "manual",

            // Determines for which views this linter will run.
            "selector": "",

            // A list of additional style definition blocks.
            "styles": [
                {
                    // Instead of 'types' you can specify error 'codes' for
                    // a style definition block
                    "codes": [""]
                }
            ],

            // The current working dir the lint job will run in.
            "working_dir": "",

            // **Only valid for PythonLinter**
            // Specify which python to use. Either a number or full path
            // to a python binary. SL will then basically use 'python -m'
            // to run the linter.
            //"python": 3,

            // **Only valid for NodeLinter**
            // If true, will *not* use a globally installed binary
            "disable_if_not_dependency": false
        }
    }
}

**Comment by kaste** [comment]
🎉
