### ISSUE TITLE
The ckhtex linter package does not work on my computer.

### ISSUE THREAD

**Issue by etienne-monier** [SublimeLinter/SublimeLinter-chktex#16]
Hi, I'm sorry to let the first issue, but it seems that's the best place in my case.

1. The SublimeLinter package is installed for me and works well for python.
2. `chktex`  is installed on my laptop and works also.
3. The SublimeLinter-chktex package is installed and *is activated* on SublimeText (I re-installed it before sending this issue).
4. Here is my SublimeLinter config:

```
{
    "linters": {
        // The name of the linter you installed
        "flake8": {
           // Flakes8 config
        },

        // For LaTeX
        "chktex": {
            // Disables the linter. The default here is 'not set'
            "disable": false,

             // Path to the executable to be used. Either a string or an
            // array. E.g. ['nvm', 'exec', '8.6', 'eslint']
            "executable": ["chktex"],

            // Suppress errors that match the the given pattern(s).
            // Either a 'string' or an 'array'. Each input string is handled as
            // a case-insensitive regex pattern and matched against the
            // error_type, code, and message. If it matches, the error will be
            // thrown away.
            // E.g. ["warning: ", "W3\d\d: ", "missing <!DOCTYPE> declaration"]
            "filter_errors": ["Warning 9",
                              "Warning 10", 
                              "Warning 44", 
                              "Warning 8", 
                              "Warning 13", 
                              "Warning 24",
                              "Warning 41"],

            // Lint mode determines when the linter is run. The linter setting
            // will take precedence over the global setting.
            "lint_mode": "background",

            // Determines for which views this linter will run.
            "selector": "source.tex, source.latex",

        },

    },
}
```

Conclusion: It does not work. I cannot lint this view with Click-right button, it stays gray.

**Additional info** : I use Ubuntu 16.04 LTS.

Could you explain what's wrong ?
Thanks !

**Comment by etienne-monier** [comment]
Oh, strange ... The default selector works.
Well, I just defined the selector as I usually use .tex and .latex files for LaTeX documents. But I can't understand why the selector was incorrect :s 

By the way, it now lint the view, but I got the following error:

```
SublimeLinter: #3 chktex Chapitre2.tex ERROR:
=============================================

  Execution failed

  [Errno 2] No such file or directory: 'chktex'

  /home/etienne/ownCloud/Manuscrit  (working dir)
  $ cat sections/Chapitre2.tex | chktex -wall -f%l:%c %k %k %n: %m
 --erroron 16 --nowarn 22 --nowarn 30 --inputfiles=0
```

I've tried to launch `cat sections/Chapitre2.tex | chktex`in a console and I got normal behaviour. What's wrong, now ?

**Comment by kaste** [comment]
You probably don't need to set executable as well. Otherwise try the absolute path to the binary.

**Comment by etienne-monier** [comment]
Well, the problem is solved, but I do not understand what was the problem :s 
Thanks for your help :)

**Comment by kaste** [comment]
The defaults would have worked 🤫
