### ISSUE TITLE
How to configure chktex with chktexrc?

### ISSUE THREAD

**Issue by sunew** [SublimeLinter/SublimeLinter-chktex#9]
I need to set the allowed length of dashes as described in the chktexrc file: WordDash = 2 instead of three, as this is the danish style of an interword dash. 

But the changes I make in the /etc/chktexrc file does not seem to be picked up by the plugin - I still get Waring 8 for '--' instead of '---'

Should the rc file have effect?

**Comment by adamaltmejd** [comment]
Did you try to put it in your home folder?

**Comment by sunew** [comment]
thank you :) - it works.
